spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/finapp
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 60000
      minimum-idle: 1
  liquibase:
    change-log: classpath:liquibase/changelog/changelog.yml